version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: HueHook.sln
  verbosity: minimal
after_build:
- cmd: 7z a HueHook-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\HueHookServer\bin\%CONFIGURATION%\*.exe %APPVEYOR_BUILD_FOLDER%\HueHookServer\bin\%CONFIGURATION%\*.dll %APPVEYOR_BUILD_FOLDER%\HueCmd\bin\%CONFIGURATION%\*.exe
artifacts:
- path: HueHook-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip
deploy:
- provider: GitHub
  description: '`HueHook-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip` contains the program (HueHookServer.exe) and all needed library files (*.dll).\n\n#### Last commit message\n%APPVEYOR_REPO_COMMIT_MESSAGE%'
  auth_token:
    secure: 9pN0zXgw1jNaPCo0m14eC3+IUZPy/y4zL/kdbdzvcMIDcT1zpkPwYF1LijP5EB+J
  prerelease: true
